### ISSUE TITLE
Supported os's

### ISSUE THREAD

**Issue by imaffett** [NodeSquarespace/node-squarespace-server#168]
What os/platforms does this support?  I can't install this on OS X/El Capitan because of /usr/share being locked down (unicode install fails).

I've tried on Ubuntu 14.04 with Node v4.1.2 and 5.0.0, but get various issues with install.  On 4.1.2 keytar fails to install.

**Comment by jasonbarone** [comment]
I'm not sure on platform support but it definitely works on OS X latest. The two most common issues I've seen are a failure to install because the user wasn't installing without using `sudo`, and a failure to install because of not accepting the terms of service agreement from xcode. I believe the latter has to do with keytar needing some sort of permissions.

Unfortunately I haven't run into the error in awhile so I might not be giving you 100% accurate information :)

**Comment by imaffett** [comment]
@jasonbarone  you sure about OS X and El Capitan?  The unicode dependency tries to install in /usr/share which is blocked.  See http://apple.stackexchange.com/questions/193368/what-is-the-rootless-feature-in-el-capitan-really  on why it will fail.    I can get it to install, but then it fails trying to find the unicode module

```
Error: Cannot find module 'unicode/category/So'
```

I tried using sudo and I use XCode daily (and the command line tools), so the TOS is not an issue.

**Comment by jasonbarone** [comment]
Ya I'm on El Capitan and have used this cli tool for awhile now. 

I mean to say XCode's command line tools, `xcode-select --install`. I recall reading about the El Capitan root issue and install `xcode-select` and agreeing to the terms in the command line made all of my permission problems go away after upgrade. FYI, I also don't work as a root user and instead use `sudo` when installing global tools.

What about trying to uninstall and reinstall xcode-select?

**Comment by kitajchuk** [comment]
@imaffett - To answer your question in general, no OS testing has been done for this tool. I've been running this tool on my MAC since I think Mavericks. I've always just developed on my working MAC and have not done any testing, especially on Windows. This tool has always been a "build it as you need it" project given its nature.

As for the issue you're having, I haven't directly experienced it. I do know that due to some of the dependencies the server currently uses you need to be running node `v0.4.6` at max right now. I plan on updating the server so this isn't a problem anymore but up to this point I haven't had a direct need that requires me to make this change.

**Comment by imaffett** [comment]
@kitajchuk  - thanks.  After the outage over the weekend in NYC, and this, we've moved away from Squarespace. 

thanks!
