### ISSUE TITLE
Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by j2is** [NodeSquarespace/node-squarespace-server#184]
Hi,

When trying to locally run the Lange theme I run into this error when running the server:
![screen shot 2016-06-03 at 02 12 01](https://cloud.githubusercontent.com/assets/6705382/15765845/2de3ed78-2931-11e6-926a-da8528cb4404.jpg)

I have a page set as the home page, I am the admin, have registered as a developer and template is in development mode. Any insight would be much appreciated, thank you.

**Comment by kitajchuk** [comment]
Not positive. I think I'll have to test locally with this template to try and figure out what is going on.

**Comment by j2is** [comment]
Thanks that would be amazing

**Comment by henwen** [comment]
👍🏼 Having this issue as well with the Ishimoto theme. Good to hear I'm not alone.

**Comment by kitajchuk** [comment]
@henwen I worked a little with @j2is on the side to help debug what was going on. It looks like the way some of the new templates are being authored by Squarespace is totally blowing up the node server. In this case it turned out to be an interestingly weird way they were using `squarespace:navigation` tags for classname rendering. The node server just doesn't parse it the way its being used. It was the first time I've seen usage of the tags like that.

Anyway, Squarespace keeps updating stuff like that and it breaks the node server more. I believe they plan on releasing a dev server sometime soon - I'm already testing the beta version of it along with others. So, hopefully soon everyone can just use that tool and this project can end since its getting to be too much of a burden to maintain as its always behind and cannot account for all template scenarios.

**Comment by henwen** [comment]
Thanks for the update @kitajchuk – I really appreciate the work and totally understand your decision to pause the project.
