### ISSUE TITLE
Site CSS retain template.conf order

### ISSUE THREAD

**Issue by kitajchuk** [NodeSquarespace/node-squarespace-server#47]

**Comment by shamroze** [comment]
Hello @kitajchuk  :) 

this is my template.conf

  "stylesheets" : [ "base.less", "bootstrap.css", "style.css" ],

  "systemCollections" : [ "products", "gallery" ],

  "server": {
    "siteurl": "https://******.squarespace.com",
    "sandbox": true
  }

and the issue is as per the order it should first load the bootstrap.css and then style.css and i have an element ,like this 

 <button type="button" class="btn btn-large orange-btn">Learn more</button>
whereas the btn class is from bootstrap and btn-large is my custom class written under stlye.css

Interestingly, on localhost the btn-large class gets overridden by btn class and on the actual site url its showing up how it is supposed to be that btn-large styles are being applied on the button.. basically on localhost my styles are not getting overridden despite of being loaded after the bootstrap unless i do !important. any help on this would be great :)

**Comment by kitajchuk** [comment]
@shamroze - There's currently no solid resolve to the [issue you are having](https://github.com/NodeSquarespace/node-squarespace-server/issues/10). It's been logged and discussed in the past, but may really need to be addressed now. As it stands, the local server loads local css on top of the remote. That being said, if you delete a property locally, not change it, the remote css will still render the old style. I have been working around it personally because I am aware of it.

I'm going to rename this issue and keep it open to track against. It would be nice to resolve this issue after all :)

**Comment by shamroze** [comment]
@kitajchuk  sure :) will be waiting for it to get resolved !!
