### ISSUE TITLE
Support all Squarespace predicates

### ISSUE THREAD

**Issue by kitajchuk** [NodeSquarespace/node-squarespace-server#8]

**Comment by ryanleichty** [comment]
I'm having issues with ".main-image?" working on my site. Everything else loads correctly except for this predicate, so most of the images are missing. It works correctly on the live site however: http://www.citieschurch.com/

I double checked that I'm running the latest version of the server and everything, but I can't figure out what the issue is.

Do you have any ideas of what I might be missing?
